### ISSUE TITLE
Json file get corrupted when simprod is not closed properly

### ISSUE THREAD

**Issue by mreboud** [marinang/SimProd#18]
From Mattermost:
The jobs file simprod.simjob get corrupted when simprod is not closed properly.
The spurious characters at the end of the file can be removed by hand, but a better solution would be useful.

Possible solutions:
 - the corrupted json files always has the same patterns, so a function can be designed to remove the additional characters.
 - having a folder with the history copy of the simjobs.json at different times, such that if the last one gets corrupted the previous one can be read.

**Comment by mreboud** [comment]
The main problem that I see is to ensure that no job is lost. I would say that if the pattern is always the same, removing the few useless characters is the simplest.

**Comment by marinang** [comment]
I've implemented a function to fix the corrupted db/jsfile in https://github.com/marinang/SimProd/commit/d2f35716d1674eb86a5915f62b87bcb82e75a577.

If the db cannot be fixed then an error is raised saying to post and issue with the `simjobs.json` file attached. Feel free to close this issue and open a new issue if you can reproduce the bug.

You can also leave this issue open until you reproduce the bug if you prefer.
